### ISSUE TITLE
Cant find documentation

### ISSUE THREAD

**Issue by timkovik** [yannbf/ionic2-components#110]
**I'm submitting a ...**  (check one with "x")

[ ] bug report
[ ] feature request
[ ] support request

**Steps to reproduce the bug:**

**Related code:**
```
    insert any relevant code here
```

**Important information:**

**Comment by yannbf** [comment]
Hey @timkovik, thanks for opening an issue!
This project is more of a kitchen sink rather than an actual component library. There is not really much documentation, it's just a matter of going through the project and seeing what is fit to be copied to your own project. I will be closing this issue as it's non-applicable but feel free to reach me on twitter @yannbf if you need any support!
